run:
	g++ -o num1.o num1.cpp -I/path/to/boost/include -L/path/to/boost/lib -lboost_iostreams
	./num1.o


clean:                                                     
	rm -f *.o  *~ *.a *.so *.x core core* a.out; rm -rf ${LIB_DIR}